name = "recipes-pwa"
main = "worker/index.ts"
compatibility_date = "2024-09-23"
workers_dev = true
pages_build_output_dir = "dist"

routes = [
  { pattern = "recipes-pwa.everyday-apps.org/api/*", zone_name = "everyday-apps.org" }
]

[[r2_buckets]]
binding = "RECIPES_BUCKET"
bucket_name = "pascals-recipes"
preview_bucket_name = "pascals-recipes"

[vars]
ALLOWED_USERS = "Claudia,Pascal"

[observability.logs]
enabled = true
invocation_logs = true
